name: Triplicate CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code_cleaniness_checks:
    name: Formatting Checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: nightly
          components: rustfmt, clippy
      - uses: actions/checkout@v4
      - run: cargo fmt --check
      - run: cargo clippy
  tests:
    needs: code_cleaniness_checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: nightly
      - uses: actions/checkout@v4
      - run: cargo test --verbose
      - run: cargo doc --verbose
  miri:
    needs: code_cleaniness_checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: nightly
          components: miri
      - uses: actions/checkout@v4
      - run: cargo miri setup
      - run: cargo miri test
